runtime: java
env: standard
runtime_config:
  jdk: openjdk8
service: dialog-flow
handlers:
- url: /.*
  script: this field is required, but ignored
manual_scaling: 
  instances: 1
resources:
  memory_gb: 4